# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fastReg <- function(y, x, w) {
    .Call('MatchItSE_fastReg', PACKAGE = 'MatchItSE', y, x, w)
}

cppKMsqSum <- function(m, c, w) {
    .Call('MatchItSE_cppKMsqSum', PACKAGE = 'MatchItSE', m, c, w)
}

cppWeightedBootstrap <- function(Ys, ts, ws, Ns, MaxIter = 1e4L) {
    .Call('MatchItSE_cppWeightedBootstrap', PACKAGE = 'MatchItSE', Ys, ts, ws, Ns, MaxIter)
}

